// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ikulboackbxhpvcusaro.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlrdWxib2Fja2J4aHB2Y3VzYXJvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk3MDc4MzQsImV4cCI6MjA2NTI4MzgzNH0.e6KMjrPr1JqeuELjEdK1F31cXbjFP1tG4JIdhtVCsBM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);